### ISSUE TITLE
CustomData of CatalogItem and StoreItem

### ISSUE THREAD

**Issue by kamyker** [PlayFab/API_Specs#93]
Is there any reason why CustomData of CatalogItem is type string and CustomData of StoreItem  type object?

**Comment by pgilmorepf** [comment]
Is this the legacy specs, or the swagger specs?
I can confirm that there's a bug in the swagger specs, where it doesn't describe dictionaries properly, but instead is describing the value-type of the dictionary.
So instead of "string" it should be "Dictionary<string, string>" or instead of "object" it should be "Dictionary<string, object>"

I believe that's the bug you're referring to, and there'll be a patch on the swagger docs for this at some point. (We haven't fully converted to using the Swagger specs internally yet).

**Comment by kamyker** [comment]
Yes probably Swagger, the one used in Unity sdk generator.

**Comment by kamyker** [comment]
For example is in this file: [Client.swagger.json]{./Swagger/PlayFab/Client.swagger.json}
`
    "StoreItem": {
         (...)
        "CustomData": {
          "type": "object"
        },
`

`
    "CatalogItem": {
          (...)
        "CustomData": {
          "type": "string"
        },
`

**Comment by pgilmorepf** [comment]
For clarity:
The SdkGenerator still uses the old legacy specification documents.

The legacy specification is "more correct", in that it's been rigorously tested, and it's what we use to generate the SDKs via SdkGenerator.

CatalogItem:
https://github.com/PlayFab/API_Specs/blob/master/Legacy/PlayFab/Client.api.json#L692
This allows a string, which we loosely intend to be a json string that you [de]serialize yourself (but can be arbitrary).

ItemInstance:
https://github.com/PlayFab/API_Specs/blob/master/Legacy/PlayFab/Client.api.json#L6427
This allows a Dictionary<string, string>

StoreItem:
https://github.com/PlayFab/API_Specs/blob/master/Legacy/PlayFab/Client.api.json#L11256
This allows an arbitrary object, which will be serialized as json, and there is a restriction on the total length of that final json string, but otherwise has no strict required structure.

The swagger documents generate the Documentation on the MSDN, and it's known that we have a bug where:
Dictionary<string, TYPE> will be displayed as just "object". So the real specification is slightly more strict than what we describe, which is a known bug.

You can see the differences on each object:
CatalogItem is still a string, which is right
https://github.com/PlayFab/API_Specs/blob/master/Swagger/PlayFab/Client.swagger.json#L6442

ItemInstance is described as an object, which is misleading and slightly less strict than reality. It should be Dictionary<string, string>
https://github.com/PlayFab/API_Specs/blob/master/Swagger/PlayFab/Client.swagger.json#L11010

And StoreItem displays as an arbitrary object, which is correct:
https://github.com/PlayFab/API_Specs/blob/master/Swagger/PlayFab/Client.swagger.json#L14209

Now that I understand your original question, the answer is: Each one of these was written in a different year, in roughly this order. We clarified and expanded the capabilities of the next ones when they were created.
Is this ideal: no. Sorry.

So, as for the "issue":
Yes, the Swagger specification is slightly under-described, but not necessarily in-accurate.
If you want absolute clarity, you can look at the legacy document for now.
Otherwise, the difference in definition for these objects is deliberate, if confusing. Again, sorry.

The swagger definition has already been filed as a bug internally, so I'm going to close this issue here. The lack of consistency with CustomData in each different item object is unfortunate, but by-design.

Thanks for your feedback.
If you want to have further discussion about the inconsistency of those 3 fields, I think the best place for you to do that is on our forums:
https://community.playfab.com/index.html
